DROP TABLE IF EXISTS outfit;
DROP TABLE IF EXISTS person;

CREATE TABLE IF NOT EXISTS person (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    age INTEGER,
    favorite_composer VARCHAR(255),
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS outfit (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    person_id BIGINT NOT NULL,
    gloves VARCHAR(255),
    hat VARCHAR(255),
    legs VARCHAR(255),
    shoes VARCHAR(255),
    top VARCHAR(255),
    FOREIGN KEY (person_id) REFERENCES person(id) ON DELETE CASCADE
);
